use_frameworks!

platform :ios, '9.0'

target 'XDUIExtension_Example' do
  pod 'XDUIExtension', :path => '../'

  target 'XDUIExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
